### PR TITLE
Landing Page - Requirement 1

### PR DESCRIPTION
**Pull request by ppauliuchenka02**
Please review and test changes for landing page requirement 1.
Connection to NewsAPI is commented on the page GeneralPage.js.

Some articles that are displayed on each designated page are missing image, author or description is because it is missed due to been structured a bit different from others or it is simply a video. 

#helpwanted to work on it so it looks much better on user visual side.

#newfeature added a footer the pages.

image
image

### CODE REVIEW

**Review by snaramirez872 — COMMENTED** [review]
everything looks good on my end

**Comment by ppauliuchenka02** [comment]
if you ran into this issue, just create an API key associated with your email and plug it into the code. I don't know why it happens because api key shouldn't be overwhelmed with requests.

image

**Comment by ChowChowSonic** [comment]
My error looks differenton my end 
image

**Comment by ppauliuchenka02** [comment]
> My error looks different on my end. Not sure if it's the same thing as you, or we're just on different redwoodjs versions or something.
> image

in GeneralPage.js replace line 13 with this ``'&apiKey=09610701367a48349b3fe5d64c9f3d9b';`` it is a new api key. let me know if you still have an issue. when I re ran on my computer I got a different error as I mentioned earlier.

**Comment by ChowChowSonic** [comment]
Using the other key fixes the error entirely; i'll get myself a key right now, and the website looks good to me.

**Review by ChowChowSonic — APPROVED** [review]
Approving the changes. The key in its current state will need to be replaced, but that's ok since we each need a private key to use anyway.

**Review by snaramirez872 — APPROVED** [review]
ready to merge

**Comment by ppauliuchenka02** [comment]
> Approving the changes. The key in its current state will need to be replaced, but that's ok since we each need a private key to use anyway.

I'll work on it so it is easier for us to plug in api key in one spot not every page.

**Pull request merged**
