### PR TITLE
Added Username and Password Constraints to Sign Up Page

### PR DESCRIPTION
**Pull request by snaramirez872**
After reviewing my code, please only merge my commits to the `SignupPage.js` file from today (June 11th). All of the other commits made BEFORE June 11th are ALREADY in the `sprint-1` branch.

### CODE REVIEW

**Comment by snaramirez872** [comment]
Conflicts should already be resolved as well in Sprint-1. The only changes that need to be merged over as I said are the ones for the SignupPage.js file

**Comment by ChowChowSonic** [comment]
your newer commits look good, but I see that there are some conflicts with sprint-1 from the older ones. I can't resolve them manually; Paulina if you can resolve them for us i'd say it looks good.

**Comment by ppauliuchenka02** [comment]
commits look good, but conflicts are stupid 
image

**Comment by ppauliuchenka02** [comment]
merged Signup page on my side locally. There is a message for incorrect username but as for password it does not allow to proceed but there is no message:

image

**Pull request closed without merging**
