### PR TITLE
Database Updates

### PR DESCRIPTION
**Pull request by cdb24**
Added:
- New options for the user profile in the database allowing them to select preferred news topics
- test cases to test out the functionality of the database

### CODE REVIEW

**Review by snaramirez872 — APPROVED** [review]
After confirming that the tests indeed still work anyway, these files look good to merge.

**Review by ChowChowSonic — CHANGES_REQUESTED** [review]
The code works, but I would remove that error message for our final submission because it's intentional there. Just so the professor doesn't think something isn't working on our end.

**Review by ppauliuchenka02 — APPROVED** [review]
good to go.
image

**Review by snaramirez872 — APPROVED** [review]
db.test.js is good to go
image_2023-06-19_160214093

**Review by ChowChowSonic — APPROVED** [review]
Approved

**Pull request merged**
