### PR TITLE
Extra Feature

### PR DESCRIPTION
**Pull request by ppauliuchenka02**
different fields of the game are done

### CODE REVIEW

**Review by ppauliuchenka02 — COMMENTED** [review]
added on screen keyboard

**Comment by ppauliuchenka02** [comment]
starts looking beautiful

few rules to keep in mind:
- if there is an apostrophe (') do not place it in a bubble
- if there is a space in the word have a bigger space between bubbles, don't put it into the bubble

image

**Comment by ppauliuchenka02** [comment]
image

**Comment by ChowChowSonic** [comment]
I'll get to work on saving the score from the database ASAP, let me know if there are any issues with my implementation after i'm done.

**Review by ppauliuchenka02 — COMMENTED** [review]
this commit has a bug: if word has repetitive letters like B in Bubble, it will display only one B

**Comment by ppauliuchenka02** [comment]
well it stopped working, so two commits above is working one

**Comment by ppauliuchenka02** [comment]
still has few bugs, didn't implement db need to finish other project parts

**Comment by snaramirez872** [comment]
Everything runs well on my machine, looks good

**Pull request merged**
