### PR TITLE
Optimized News Pages

### PR DESCRIPTION
**Pull request by ppauliuchenka02**
somehow broke Search and cannot see what's wrong, yaks sorryyy

### CODE REVIEW

**Review by ppauliuchenka02 — COMMENTED** [review]
works perfectly :) thank you

**Comment by ppauliuchenka02** [comment]
Updated pagination, it has few bugs on last 2 pages which is weird not sure yet how to fix.

@ChowChowSonic I had to keep pageSize outside url so that I can get a full count of articles for pagination to determine number of pages.

**Review by ChowChowSonic — APPROVED** [review]
Looks good to me. LGTM!

**Review by ppauliuchenka02 — COMMENTED** [review]
actually just found one little bug, since all of the categories are on homepage, after getting results from search it's output is under each category. can you change it so that results are displayed when there is no category so other are untouched setState('').

just for reference how articles are located under each category
image

**Comment by ppauliuchenka02** [comment]
> Looks good to me. I'm not seeing any bugs on my end. I'm approving for now, but if you want to fix feel free to between now and merge.

do you have this issues, except home and general (dunno why but it is not affected)? well home has this issue when preferences are set to more options than general

Screenshot 2023-07-02 at 19 11 51
Screenshot 2023-07-02 at 19 11 54
Screenshot 2023-07-02 at 19 11 57

**Comment by ppauliuchenka02** [comment]
here is more to bugs



Screenshot 2023-07-02 at 19 21 30

**Comment by ChowChowSonic** [comment]
The error with the blank pages has more to do with the limited availability of articles from newsapi. If I recall correctly, they only have 100 articles that can be sent out to developers. Once they run out of articles, they don't send us anything, and we start getting pages that are blank like the last image you posted. That's not a bug, that's completely normal and expected because we're only on developer licenses.

**Comment by ppauliuchenka02** [comment]
it is some weird stuff. so general and science categories on pagination work amazing but for whatever reason there are still bugs when you are testing it on different categories lmao.


so here how it looks when you reach out maximum articles per category in general or science aka 1st and last
image
image


and when on a different category it looks smth like that:
news articles on pages 5 & 6 are exactly the same. We can add a **fixed** checkpoint that 5 page is the last page but it is not good. On page 5 arrows > and >> should simply look disabled.
image
image

**Comment by ppauliuchenka02** [comment]
> The error with the blank pages has more to do with the limited availability of articles from newsapi. If I recall correctly, they only have 100 articles that can be sent out to developers. Once they run out of articles, they don't send us anything, and we start getting pages that are blank like the last image you posted. That's not a bug, that's completely normal and expected because we're only on developer licenses.

right, I forgot about that.

**Review by snaramirez872 — APPROVED** [review]
everything looks good on my end

**Pull request merged**
