### PR TITLE
Settings Page Update 1

### PR DESCRIPTION
**Pull request by ChowChowSonic**
The settings page is functioning properly, and thanks to Sean's help so are database mutations.

### CODE REVIEW

**Comment by cdb24** [comment]
fixed an issue with one of the test cases failing, tests all run with not issues now and we can merge this into main now

**Review by cdb24 — APPROVED** [review]

**Review by ppauliuchenka02 — CHANGES_REQUESTED** [review]
once preferences are selected and submitted DB is not updated, nor selected elements are reflected on user side as well.

**Review by ppauliuchenka02 — DISMISSED** [review]
it updates db only once for one user

to receive some changes in db, I ran ``yarn rw prisma migrate dev`` and received nothing

than I ran ``yarn rw prisma db push`` selected new preferences  and received an update of db, logged in under new user made changes to preferences but db is not updating. with more users same thing.

image

**Comment by snaramirez872** [comment]
By default the User has 'General' already selected. Below is a screenshot of a manual test I did where I made a new User by the name of 'seantest4' and then I went to our settings page.

Screenshot 2023-06-20 222535

Updating preferences also works on my end. Below is another manual test I did where I made a new User by the name of 'seantest6', went to the settings page, selected 'Business', saved, then went back to the settings page and took this screenshot

Screenshot 2023-06-20 223420

**Review by snaramirez872 — APPROVED** [review]
Everything looks good and runs well on my end.

**Review by cdb24 — APPROVED** [review]
Website loads and runs correctly, I checked to confirm that the database was updated 
Before:
image

and after:
image

I tried it a second time, and it looks like it went through;
image

After taking a look at what may have been the cause, Prisma Studio will prevent any mutations from taking effect until the prisma studio page is refreshed. It appears that the settings page is working properly now. Furthermore, attempting to turn off the general news toggle in the settings page will result in it always switching back on and showing up as True in the database.

The test cases were updated accordingly to reflect the changes to the Schema file, the users.js file, and the users.sdl.js files.

As everything regarding the setting pages seem to be working, I'll be approving this merge request.

**Review by cdb24 — APPROVED** [review]

**Review by cdb24 — APPROVED** [review]

**Pull request merged**
