### PR TITLE
Dark theme

### PR DESCRIPTION
**Pull request by cdb24**
Made the dark mode implementation which includes a toggle button, it looks like everything's working atm

### CODE REVIEW

**Review by ppauliuchenka02 — CHANGES_REQUESTED** [review]
I receive an error after trying to run the project in dev mode
image

**Comment by snaramirez872** [comment]
I'll take a look at it when i get to campus; I'll be there in like 20-30 minutes.

**Review by snaramirez872 — APPROVED** [review]
looks good

**Review by ppauliuchenka02 — APPROVED** [review]
for whatever reason had to run ``yarn add --dev @babel/plugin-proposal-private-property-in-object`` to get rid of my error
everything is working! preference is saved when you logout and login!

**Pull request merged**
